version: 2.1
jobs:
  build:
    docker:
      - image: node:18.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npx mocha --exit

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
